export default [
  { name: "Python" },
  { name: "JavaScript" },
  { name: "Java" },
  { name: "C++" },
  { name: "Go" },
  { name: "Ruby" },
  { name: "Swift" },
  { name: "Kotlin" },
  { name: "PHP" },
  { name: "TypeScript" },
  { name: "C#" },
  { name: "Rust" },
  { name: "Perl" },
  { name: "Lua" },
  { name: "R" },
  { name: "MATLAB" },
  { name: "Dart" },
  { name: "Scala" },
  { name: "Haskell" },
  { name: "Objective-C" },
  { name: "Elixir" },
  { name: "Erlang" },
  { name: "F#" },
  { name: "Fortran" },
  { name: "Lisp" },
  { name: "Prolog" },
  { name: "Julia" },
  { name: "C" },
  { name: "Visual Basic" },
  { name: "Shell" },
  { name: "SQL" },
  { name: "Assembly" },
];
